homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 192
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

http:
  api_password: !secret http_password
  use_x_forwarded_for: True
  ip_ban_enabled: True
  login_attempts_threshold: 3

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: True

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

ios:

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_key

device_tracker:
  - platform: unifi
    username: !secret unifi_user
    password: !secret unifi_pass
    host: unifi
    verify_ssl: false
    track_new_devices: false
  - platform: nmap_tracker
    hosts: !secret nmap_hosts


group: !include groups.yaml
automation: !include_dir_list automations
script: !include_dir_merge_named scripts

switch: !include devices/switches.yaml
lock: !include devices/locks.yaml
sensor: !include devices/sensors.yaml
binary_sensor: !include devices/binary_sensors.yaml
fan: !include devices/fans.yaml
