alias: "Back Door unlocked"
hide_entity: true
trigger:
  platform: state
  entity_id: lock.back_door_locked
  from: "locked"
  to: "unlocked"
action:
  service: notify.ios_gylfaginning
  data: 
    message: "Back Door unlocked"