alias: "Everyone left"
hide_entity: true
trigger:
  platform: state
  entity_id: group.all_devices
  to: "not_home"
  for:
    hours: 1
action:
  - service: notify.ios_gylfaginning
    data:
      message: "Everyone left; setting house to away"
  - service: lock.lock
  - service: script.turn_playroom_off
  - service: climate.set_temperature
    entity_id: climate.downstairs_thermostat_cooling_1
    data:
      temperature: 73
  - service: climate.set_temperature
    entity_id: climate.downstairs_thermostat_heating_1
    data:
      temperature: 64
