alias: "I'm back"
hide_entity: true
trigger:
  platform: state
  entity_id: device_tracker.gylfaginning, device_tracker.kristensiphone
  to: "home"
  from: "not_home"
action:
  - service: notify.ios_gylfaginning
    data_template:
      message: "{{ trigger.entity_id }} is back"
  - service: climate.set_temperature
    entity_id: climate.downstairs_thermostat_cooling_1
    data:
      temperature: 69
  - service: climate.set_temperature
    entity_id: climate.downstairs_thermostat_heating_1
    data:
      temperature: 68
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.vacation_mode
