alias: "Morning 6 AM"
hide_entity: true
trigger:
  platform: time
  at: "06:00:00"
condition:
  condition: state
  entity_id: input_boolean.vacation_mode
  state: "off"
action:
  - service: climate.set_temperature
    entity_id: climate.downstairs_thermostat_cooling_1
    data:
      temperature: 69
  - service: climate.set_temperature
    entity_id: climate.downstairs_thermostat_heating_1
    data:
      temperature: 68

