alias: "No playroom motion"
trigger:
  platform: state
  entity_id: binary_sensor.playroom__motion_sensor
  from: "on"
  to: "off"
condition:
  # only fire if off for 30 minutes
  condition: state
  entity_id: binay_sensor.playroom__motion_sensor
  state: "off"
  for:
    minutes: 30
action:
  service: script.turn_playroom_off
