alias: "Playroom motion detected"
hide_entity: true
trigger:
  platform: state
  entity_id: binary_sensor.playroom__motion_sensor
  from: "off"
  to: "on"
action:
  - service: script.turn_playroom_on
