alias: "No playroom motion"
hide_entity: true
trigger:
  platform: state
  entity_id: binary_sensor.playroom__motion_sensor
  from: "on"
  to: "off"
  for:
    minutes: 30
action:
  service: script.turn_playroom_off
